import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/sections/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: '#fbf9f5', // mapped to stitch background
        foreground: 'hsl(var(--foreground))',
        "on-tertiary-fixed": "#281525",
        "on-secondary-fixed-variant": "#673d00",
        "tertiary-fixed-dim": "#ddbdd3",
        "tertiary-container": "#2d1929",
        "secondary-container": "#fdb96a",
        "on-surface-variant": "#454840",
        "on-secondary": "#ffffff",
        "primary-container": "#18230d",
        "secondary-fixed": "#ffddba",
        "on-tertiary-container": "#9b7f93",
        "surface-tint": "#566347",
        "primary": {
          DEFAULT: '#030a00',
          foreground: 'hsl(var(--primary-foreground))',
        },
        "secondary": {
          DEFAULT: '#865309',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#f0eee9",
        "surface-bright": "#fbf9f5",
        "inverse-surface": "#30312e",
        "secondary-fixed-dim": "#fdb96a",
        "on-surface": "#1b1c19",
        "surface-variant": "#e4e2de",
        "on-secondary-fixed": "#2b1700",
        "inverse-on-surface": "#f3f0ec",
        "surface-container-low": "#f6f3ef",
        "outline": "#75786f",
        "tertiary": "#120310",
        "on-primary-fixed": "#141f09",
        "inverse-primary": "#bdcbaa",
        "on-primary-fixed-variant": "#3e4b31",
        "primary-fixed-dim": "#bdcbaa",
        "error-container": "#ffdad6",
        "surface": "#fbf9f5",
        "on-error-container": "#93000a",
        "surface-dim": "#dcdad6",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#eae8e4",
        "on-primary-container": "#7e8c6e",
        "on-secondary-container": "#774800",
        "surface-container-highest": "#e4e2de",
        "on-tertiary-fixed-variant": "#573f51",
        "primary-fixed": "#d9e8c5",
        "outline-variant": "#c5c8bd",
        "on-background": "#1b1c19",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#fbd9ef",
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "32px",
        "unit": "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "section-gap": "120px"
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["var(--font-plus-jakarta-sans)"],
        "headline-xl": ["var(--font-noto-serif)"],
        "display-lg": ["var(--font-noto-serif)"],
        "body-md": ["var(--font-plus-jakarta-sans)"],
        "body-lg": ["var(--font-plus-jakarta-sans)"],
        "quote": ["var(--font-noto-serif)"],
        "headline-md": ["var(--font-noto-serif)"],
        sans: ["var(--font-plus-jakarta-sans)"],
        serif: ["var(--font-noto-serif)"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "quote": ["24px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config